### ISSUE TITLE
Expected delay on Android push notifications?

### ISSUE THREAD

**Issue by quantumproducer** [vkatsuba/epns#1]
Hello, thank you for this library.

I am trying this:
```erlang
sample() ->
  FCMData = #{
  key => "mykey",
  url => "https://fcm.googleapis.com/fcm/send",
  playload => #{
    to => <<"mytoken">>,
    priority => <<"high">>,
    data => #{
      <<"title">> => <<"Your Turn">>,
      <<"some_custom_field">> => true
   }}},
  push(fcm, FCMData).
```
```erlang
1> epns:sample().
#{<<"canonical_ids">> => 0,<<"failure">> => 0,
  <<"multicast_id">> => 2161...,
  <<"results">> =>
      [#{<<"message_id">> =>
             <<"0:158490...">>}],
  <<"success">> => 1}
```
I see the success message but I do not see anything on the device.
When I taken the same token and send a test notification at `https://console.firebase.google.com/u/0/project/<project>/notification/compose`

I see a result within seconds on the device.

Is there some other config needed? Is a delay expected?

**Comment by vkatsuba** [comment]
Hi @quantumproducer ,

When we send push notification to the FCM service - we can see response. If you see `success` response - this mean that the notification was received by FCM and all is ok, in other case you can get error from FCM(eg, try put wrong `key`). The reason why you cannot see notification in your device is can be that you try send notification payload what not parsed by your device application as expected, eg device application can have logic - if JSON payload from FCM has some specific field - need to display alert, in other case need to ignore push notification. Try to connect with developers who develop your application and try get info about - what exactly payload should be, or try get info about - which JSON is send from `FCM` console and try build the same payload and send by `epns`.

Regards,
--V

**Comment by quantumproducer** [comment]
Hi thank you for the quick response - I am using the example^ like is in Readme.
I get "success" from FCM response not an error. I try with

  playload => #{
    to => <<"f...">>,
    title => <<"Your turn">>,
    body => <<"Your turn">>,
    priority => <<"high">>,
    data => #{
      title => <<"Your turn">>,
      body => <<"Your Turn">>
   	}
   }
  },

Using the  firebase console I can send - I am just trying to use the example in the readme to send to android device

**Comment by vkatsuba** [comment]
I provide info about error just for example, you can try send wrong `key` to see behavior of FCM with bad request. If FCM was return success in response this mean that the FCM was get push notification and will send to user with token what you put. The README example was working for few messengers, so, this is working example. So, FCM should send notification to your application in your device for this case need to be sure that your application can working with payload what you try send. If you try send push notification to your device without having mobile application the push notification cannot be displayed. But I suppose you need ask application developer for create logic in your mobile application for recive all messages from FCM and display JSON, then you can try send from `console` and from `epns` messages then you can compare payloads and change your current payload to the expected JSON payload.

**Comment by quantumproducer** [comment]
Hi, what do you mean send from console? Is there a way to view JSON for firebase console?
I try sending from Postman (HTTP debugging tool) and get the same kind of response

**Comment by vkatsuba** [comment]
When I write `console` I was mean  - `https://console.firebase.google.com/u/0/project/<project>/notification/compose`. As I described above you can ask mobile application developer create logic in mobile application to fetch to all messages from FCM and put they to some `alert` function for display JSON in your mobile device.

**Comment by quantumproducer** [comment]
Thanks will investigate
