### ISSUE TITLE
Please update Android example with notification body

### ISSUE THREAD

**Issue by quantumproducer** [vkatsuba/epns#2]
This is what worked for me - receive on device

  playload => #{
    registration_ids => [<<"your_id">>],
    priority => <<"high">>,
    notification => #{
       title => <<"Your turn">>,
       body => <<"Your turn">>
    }

Please update the Readme with the notification key.

Thank you for this library, it is very helpful :)

**Comment by vkatsuba** [comment]
This is not a issue. The example in README also work for Android, was retested. Playload can be different. I'm glad you found this library useful. Cheers!

**Comment by quantumproducer** [comment]
Ok thanks - I understand now - including the notification key is not required for the device to receive it BUT it must be there to show to user.

**Comment by vkatsuba** [comment]
> Ok thanks - I understand now - including the notification key is not required for the device to receive it BUT it must be there to show to user.

Right.
